version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    network_mode: 'bridge'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
