version: '2'

services:
  db:
    restart: always
    image: mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=fmatrion"
      - "MYSQL_PASSWORD=essai"
      - "MYSQL_DATABASE=fmatrion"
    network_mode: 'bridge'
    volumes:
      - db:/var/lib/mysql:rw
    #  - default
    dns_search:
      - db
  pma:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - VIRTUAL_HOST=pma.localhost
    #networks:
    #  - default
    dns_search:
      - pma
    network_mode: 'bridge'

  maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
      - 80
    #networks:
    #  - default
    environment:
      VIRTUAL_HOST: maildev.localhost
    dns_search:
      - maildev
    network_mode: 'bridge'

  mailcatcher:
    image: zolweb/docker-mailcatcher
    ports:
      - 1080:1080
    environment:
      - VIRTUAL_HOST=mailcatcher.localhost
      - VIRTUAL_PORT=80
    dns_search:
      - mailcatcher
    network_mode: 'bridge'

volumes:
  db: {}

