version: '2'
services:
  php:
    build: .
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html:rw
    # environment:
    #   VIRTUAL_HOST: blackfire2.localhost
    # network_mode: 'bridge'

  blackfire:
    image: blackfire/blackfire
    ports:
      - "8707:8707"
      # - 8707
    environment:
        # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
        # - BLACKFIRE_SERVER_ID
        # - BLACKFIRE_SERVER_TOKEN
        # You can also use global environment credentials :
        BLACKFIRE_SERVER_ID: cd51bbd0-1cda-4df5-be2f-c0b15989606e
        BLACKFIRE_SERVER_TOKEN: 538fba5eccbba837bfd3e7a804cba41ab6a25b014eff93dcc75d91d4049fd7ff
        BLACKFIRE_LOG_LEVEL: 4
    # environment:
    #   VIRTUAL_HOST: blackfiretcp.localhost
    # network_mode: 'bridge'
